#SALIDA DE DATOS

numero= int(input("Digite un número: "))
print(f"El número es: {numero*1}")
print(f"El número es: {numero*2}")
print(f"El número es: {numero*3}")
print(f"El número es: {numero*4}")
print(f"El número es: {numero*5}")
print(f"El número es: {numero*6}")
print(f"El número es: {numero*7}")
print(f"El número es: {numero*8}")
print(f"El número es: {numero*9}")
print(f"El número es: {numero*10}")